language: python
sudo: false
python:
  - 2.7
branches:
  only:
    - master
script:
  - pip install -r .travis.d/requirements.txt
  - make html
after_success:
  - ssh-keyscan -H $HOSTNAME 2>&1 | tee -a $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_0a43fe57bc95_key -iv $encrypted_0a43fe57bc95_iv -in .travis.d/id-rsa.enc -out .travis.d/id-rsa -d
  - mkdir -p ~/.ssh && mv .travis.d/id-rsa ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - rsync -arv --delete --progress _build/html/ $USERNAME@$HOSTNAME:/var/www/named-data.net/www/doc/ndn-ccl-api/
